### ISSUE TITLE
Guava deserialization not working when object to deserialize comes from different classloader

### ISSUE THREAD

**Issue by digitalillusion** [FasterXML/jackson-datatypes-collections#20] opened 2017-09-13 14:47 UTC
Hello,

I'm using retrofit2 to read json from an http page, but I get the following exception:

> com.fasterxml.jackson.databind.JsonMappingException: Can not find a deserializer for non-concrete Collection type [collection type; class com.google.common.collect.ImmutableList, contains [simple type, class java.lang.String]]
 at [Source: okhttp3.ResponseBody$BomAwareReader@5dd9326d; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:305)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:268)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:466)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:479)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:443)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:206)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:681)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:481)
	at com.fasterxml.jackson.databind.ObjectReader._findRootDeserializer(ObjectReader.java:1859)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1621)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)

The reason is that inside method
com.fasterxml.jackson.datatype.guava.GuavaDeserializers.findCollectionDeserializer()
the predicate ImmutableCollection.class.isAssignableFrom(raw) is returning false.
Infact _raw_ is indeed instance of  _com.google.common.collect.ImmutableList_ but from a different classloader.

I think that _raw_ should be obtained by:

`Class<?> raw = this.getClass().getClassLoader().loadClass(type.getRawClass().getCanonicalName());`

**Comment by cowtowncoder** [comment] 2017-09-13 20:21
I am not sure that is correct -- classes across class loaders do not mix. So although check might pass I don't think result would be any better since deserializer refers to different "copy" of class; from JVM perspective they are different classes despite having same name, package, and possibly bytecode.

And worse, I don't know how this could be tested.

**Comment by DotiSandhyaRani3478** [comment] 2020-04-30 04:06
Try register the Guava Module like:
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.registerModule(new GuavaModule());

**Comment by cowtowncoder** [comment] 2020-04-30 06:55
Regardless of whether the root cause is simply not having module registered (good point, that is a possibility), or if there is class loader issue, module really can not solve either problem (since if it's different classloader Jackson literally can not see the "right" types to handle). Closing.

**Closed by cowtowncoder** 2020-04-30 06:55 UTC
