### ISSUE TITLE
Have a crash with serialize guava table(row map)

### ISSUE THREAD

**Issue by Notlhos** [FasterXML/jackson-datatypes-collections#65] opened 2020-04-15 07:51 UTC
https://hastebin.com/onunuworay.js
Sometime, but not always, jackson crash my application, when he try save a Table, how can i fix it?
P.S. Offtop, but i don't know where i can ask my second question. Jackson useful with many applications? Example: My Library has one object for json(with jackson ObjectMapper) to all my projects(15 apps), and sometime jackson is work bad(can't deserialize or something, when apps starts together). Can i fix it too?

**Comment by cowtowncoder** [comment] 2020-04-15 16:08
Without a reproduction (as well as information on Jackson version, maybe platform if not J2SE), it is impossible to say what might be happening. A test case would be needed.

On other question: thank you for asking for a better forum for that (since it is bit an open-ended question). 2 suggestions:

1. Mailing list: https://groups.google.com/forum/#!forum/jackson-user 
2. Chat: https://gitter.im/FasterXML/jackson-databind

**Comment by Notlhos** [comment] 2020-04-15 18:12
https://pastebin.com/ru8takE1 - full crash log
Version: Jackson 2.10.2
![image](https://user-images.githubusercontent.com/42893543/79371774-93686580-7f5d-11ea-8a29-2c425d2f6cf9.png)
![image](https://user-images.githubusercontent.com/42893543/79371862-b85cd880-7f5d-11ea-98f1-7c9674760d94.png)
![image](https://user-images.githubusercontent.com/42893543/79371940-d9252e00-7f5d-11ea-92a4-0d672ccc4140.png)

**Comment by cowtowncoder** [comment] 2020-04-15 18:34
Seems like it goes through something called `JacksonAPI`, and runs on non-Java JVM language (Kotlin?). Jackson can not do anything about JVM crashes itself (which sounds like JVM bug; may want to try newer patch).

**Comment by kupci** [comment] 2020-04-15 21:30
From the thread dump, when it "crashes", it seems to be trying to load a file, so possible config issue (classpath?)
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 209  java.util.zip.ZipFile.getEntry(J[BZ)J (0 bytes) @ 0x00007efc61178398 [0x00007efc61178340+0x58]
J 9898 C2 java.util.jar.JarFile.getJarEntry(Ljava/lang/String;)Ljava/util/jar/JarEntry; (9 bytes) @ 0x00007efc62b30288 [0x00007efc62b2ff00+0x388]
J 10308 C2 org.bukkit.plugin.java.PluginClassLoader.findClass(Ljava/lang/String;Z)Ljava/lang/Class; (404 bytes) @ 0x00007efc62999b94 [0x00007efc62999080+0xb14]

Ideas to narrow this: add logging to see what types it is serializing here:
`com.fasterxml.jackson.databind.ser.BasicSerializerFactory.buildMapSerializer`
```

**Comment by cowtowncoder** [comment] 2023-10-17 00:39
Nothing actionable, unfortunately; closing.

**Closed by cowtowncoder** 2023-10-17 00:39 UTC
Labels: guava, need-test-case
