### ISSUE TITLE
Deserializing ImmutableMap<String,Double> fails

### ISSUE THREAD

**Issue by caeus** [FasterXML/jackson-datatypes-collections#60] opened 2019-09-26 16:31 UTC
when trying to deserialize, `let's say {"value":3.0}`
it throws this exception
`Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize Map key of type `java.lang.Double` from String "value": not a valid representation, problem: (java.lang.NumberFormatException) For input string: "value"
2019-09-26T15:57:49.276742+00:00 app[web.1]:  at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@54815ea6; pos: 6004] (through blablabla)
2019-09-26T15:57:49.276744+00:00 app[web.1]: 	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
2019-09-26T15:57:49.276750+00:00 app[web.1]: 	at com.fasterxml.jackson.databind.DeserializationContext.weirdKeyException(DeserializationContext.java:1528)
2019-09-26T15:57:49.276752+00:00 app[web.1]: 	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdKey(DeserializationContext.java:867)
2019-09-26T15:57:49.276755+00:00 app[web.1]: 	at com.fasterxml.jackson.databind.deser.std.StdKeyDeserializer.deserializeKey(StdKeyDeserializer.java:133)
2019-09-26T15:57:49.276759+00:00 app[web.1]: 	at com.fasterxml.jackson.datatype.eclipsecollections.deser.map.RefKeyHandler.key(RefKeyHandler.java:34)
2019-09-26T15:57:49.276770+00:00 app[web.1]: 	at com.fasterxml.jackson.datatype.eclipsecollections.deser.map.TypeHandlerPair$1.add(TypeHandlerPair.java:188)
2019-09-26T15:57:49.276775+00:00 app[web.1]: 	at com.fasterxml.jackson.datatype.eclipsecollections.deser.map.TypeHandlerPair$1.add(TypeHandlerPair.java:166)
2019-09-26T15:57:49.276798+00:00 app[web.1]: 	at com.fasterxml.jackson.datatype.eclipsecollections.deser.map.EclipseMapDeserializers$Entry$DeserializerImpl.deserializeEntry(EclipseMapDeserializers.java:311)`

I think it may be somehow mixing V deserializer with K deserializer

**Comment by yawkat** [comment] 2019-09-26 16:43
This looks like the issue fixed in #39 . I'm not sure what the state of 2.10 is, but it should be fixed in that release.

**Comment by cowtowncoder** [comment] 2019-09-27 01:27
Funny timing: `2.10.0` is just now released.

In future, including actual code to reproduce the issue would help a lot.

**Comment by yawkat** [comment] 2019-10-06 11:44
@caeus Did this fix your issue? If so, please close this report

**Closed** 2019-10-23 19:28 UTC
Labels: eclipsec
